### ISSUE TITLE
auto_explain documentation?

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [aiven/aiven-extras#16]
Hello,

Could you add some documentation around using `auto_explain` with Aiven's Postgres service? Searching help.aiven.io I only found https://help.aiven.io/en/articles/489557-postgresql-superuser-access which links here, and while this extension does seem to define some helper functions, they are not documented as far as I can tell.

**Comment by lornajane** [comment]
Thanks for mentioning this! The `aiven-extras` are bit of an add-on for customers who need the advanced features, and it is only active for the current session. Can you say something about what you wanted to use aiven-extras for? I would like to understand the use case and also to prioritise which area of docs should get attention first.

**Comment by uhoh-itsmaciek** [comment]
I'm actually with pganalyze and we recently added support for Aiven to our [automated EXPLAIN](https://pganalyze.com/postgres-explain) feature, which works best with `auto_explain`. We'd love to make it easier for your customers to get the most out of our service when using both together. On other platforms, we recommend enabling adding `auto_explain` to `shared_preload_libraries`, but as I understand it, that's not an option on Aiven. Would calling `auto_explain_load` after connection be the right approach?

**Comment by joukost** [comment]
Hi, thank you for mentioning this, the docs were out of date. #17 and #18 add a list of current functions and some clarifications to examples and are now merged.

`auto_explain` is loaded for the active session only - we currently don't support preloading it by default.

We have some internal tickets discussing how to ease integration of our PG services to analysis tools/platforms such as pganalyze. Please let us know if there's anything else that might be missing to achieve this in a good way.

**Comment by joukost** [comment]
I'll close this for now - feel free to reopen in case the updated docs are still too lacking or have errors. Thanks.

**Comment by uhoh-itsmaciek** [comment]
Great, thanks for the quick fix!
